// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package footer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// footer.templ — the housekeeping the app keeps in Settings/Help: who delivers,
// where, the documents, and the way out. Muted and track-divided, the way the
// app's Settings screen reads.

import "lamazon/website/templates/components/ui"

func Footer(eta string, cities []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"mt-12 border-t border-track bg-surface px-gutter py-10 pb-36\"><div class=\"mx-auto grid max-w-readable gap-8 md:grid-cols-3\"><div><h3 class=\"text-title-small\">Uniminute</h3><p class=\"mt-2 text-body text-muted\">Local shops, delivered on campus. Real stock, real prices, secure online payment or cash on delivery.</p><p class=\"mt-3 inline-flex items-center gap-2 text-small text-muted\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Icon("truck", "h-4 w-4 text-strong").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if eta != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span>Delivery in about ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(eta)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/footer/footer.templ`, Line: 18, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span>Fast campus delivery</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p></div><div><h3 class=\"text-title-small\">Shop</h3><ul class=\"mt-2 space-y-1\"><li><a class=\"flex min-h-touch items-center text-body text-muted hover:text-strong\" href=\"/shop\">All departments</a></li><li><a class=\"flex min-h-touch items-center text-body text-muted hover:text-strong\" href=\"/stores\">Stores</a></li><li><a class=\"flex min-h-touch items-center text-body text-muted hover:text-strong\" href=\"/search\">Search</a></li><li><a class=\"flex min-h-touch items-center text-body text-muted hover:text-strong\" href=\"/orders\">Your orders</a></li></ul></div><div><h3 class=\"text-title-small\">The fine print</h3><ul class=\"mt-2 space-y-1\"><li><a class=\"flex min-h-touch items-center text-body text-muted hover:text-strong\" href=\"/policies\">Policies</a></li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(cities) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<p class=\"mt-3 text-small text-muted\">Delivering in ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(joinCities(cities))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/footer/footer.templ`, Line: 39, Col: 77}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, ".</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func joinCities(cities []string) string {
	out := ""
	for i, c := range cities {
		if i > 0 {
			if i == len(cities)-1 {
				out += " and "
			} else {
				out += ", "
			}
		}
		out += c
	}
	return out
}

var _ = templruntime.GeneratedTemplate
