// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package account

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// photos.templ — PhotoManager from widgets/photo_manager.dart: the first photo
// is the cover, × removes one, arrows move one earlier or later, and the add
// control brings in more. It renders the Alpine state of the component
// around it (`shots`, `busy`, and the photo methods in static/js/app.js).

import "lamazon/website/templates/components/ui"

func PhotoManager() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<input type=\"file\" accept=\"image/*\" multiple class=\"hidden\" x-ref=\"photos\" x-on:change=\"addFiles($event)\"><template x-if=\"!shots.length\"><button type=\"button\" x-on:click=\"$refs.photos.click()\" x-bind:disabled=\"busy\" class=\"flex h-[140px] w-full flex-col items-center justify-center rounded border border-[#DDDDD8] bg-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Icon("image-plus", "h-[26px] w-[26px] text-muted").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"mt-2 text-[14px] font-bold text-text\">Add photos</span> <span class=\"mt-0.5 text-[12px] text-muted\">Every photo is framed square, so the shop lines up</span></button></template><template x-if=\"shots.length\"><div><div class=\"flex gap-2.5 overflow-x-auto pb-1 no-scrollbar\"><template x-for=\"(shot, i) in shots\" :key=\"shot.url || shot.preview\"><div class=\"relative h-[112px] w-[112px] shrink-0 overflow-hidden rounded-[14px] bg-img-ground\"><img x-bind:src=\"shot.url || shot.preview\" alt=\"\" class=\"h-full w-full object-cover\"> <span x-show=\"i === 0\" class=\"absolute left-1.5 top-1.5 rounded-[10px] bg-text px-2 py-[3px] text-[10px] font-extrabold text-white\">Cover</span> <button type=\"button\" x-on:click=\"remove(i)\" x-bind:disabled=\"busy\" aria-label=\"Remove photo\" class=\"absolute right-1 top-1 flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white text-danger shadow-[0_0_4.5px_rgba(0,0,0,0.26)]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Icon("x", "h-3 w-3").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</button><div class=\"absolute inset-x-1 bottom-1 flex\"><button type=\"button\" x-show=\"i > 0\" x-on:click=\"move(i, -1)\" x-bind:disabled=\"busy\" aria-label=\"Move photo earlier\" class=\"flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white text-text shadow-[0_0_4.5px_rgba(0,0,0,0.26)]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Icon("chevron-left", "h-3 w-3").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</button> <button type=\"button\" x-show=\"i < shots.length - 1\" x-on:click=\"move(i, 1)\" x-bind:disabled=\"busy\" aria-label=\"Move photo later\" class=\"ml-auto flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white text-text shadow-[0_0_4.5px_rgba(0,0,0,0.26)]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Icon("chevron-right", "h-3 w-3").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</button></div></div></template></div><div class=\"mt-2.5 flex items-center\"><button type=\"button\" x-on:click=\"$refs.photos.click()\" x-bind:disabled=\"busy\" class=\"inline-flex min-h-touch shrink-0 items-center rounded-full px-3 text-label text-text hover:bg-strong/[.06]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Icon("plus", "h-4 w-4").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span class=\"ml-2\">Add photos</span></button><p class=\"ml-1 flex-1 text-[12px] text-muted\" x-text=\"busy ? 'Saving…' : 'Use the arrows to reorder — the first one is the cover.'\"></p></div></div></template>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
